# Generated by Django 5.0 on 2023-12-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "titletype",
                    models.CharField(
                        blank=True, db_column="titleType", max_length=255, null=True
                    ),
                ),
                (
                    "primarytitle",
                    models.CharField(
                        blank=True, db_column="primaryTitle", max_length=255, null=True
                    ),
                ),
                (
                    "originaltitle",
                    models.CharField(
                        blank=True, db_column="originalTitle", max_length=255, null=True
                    ),
                ),
                (
                    "isadult",
                    models.CharField(
                        blank=True, db_column="isAdult", max_length=255, null=True
                    ),
                ),
                (
                    "startyear",
                    models.CharField(
                        blank=True, db_column="startYear", max_length=255, null=True
                    ),
                ),
                (
                    "endyear",
                    models.CharField(
                        blank=True, db_column="endYear", max_length=255, null=True
                    ),
                ),
                (
                    "runtimeminutes",
                    models.CharField(
                        blank=True,
                        db_column="runtimeMinutes",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("genres", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "film",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CastShort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                ("directors", models.CharField(blank=True, max_length=255, null=True)),
                ("writers", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "cast-short",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FilmShort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "titletype",
                    models.CharField(
                        blank=True, db_column="titleType", max_length=255, null=True
                    ),
                ),
                (
                    "primarytitle",
                    models.CharField(
                        blank=True, db_column="primaryTitle", max_length=255, null=True
                    ),
                ),
                (
                    "originaltitle",
                    models.CharField(
                        blank=True, db_column="originalTitle", max_length=255, null=True
                    ),
                ),
                (
                    "isadult",
                    models.CharField(
                        blank=True, db_column="isAdult", max_length=255, null=True
                    ),
                ),
                (
                    "startyear",
                    models.CharField(
                        blank=True, db_column="startYear", max_length=255, null=True
                    ),
                ),
                (
                    "endyear",
                    models.CharField(
                        blank=True, db_column="endYear", max_length=255, null=True
                    ),
                ),
                (
                    "runtimeminutes",
                    models.CharField(
                        blank=True,
                        db_column="runtimeMinutes",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("genres", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "film-short",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PersonFilmShort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                ("ordering", models.CharField(blank=True, max_length=255, null=True)),
                ("nconst", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("job", models.CharField(blank=True, max_length=255, null=True)),
                ("characters", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "person-film-short",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PersonShort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nconst", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "primaryname",
                    models.CharField(
                        blank=True, db_column="primaryName", max_length=255, null=True
                    ),
                ),
                (
                    "birthyear",
                    models.CharField(
                        blank=True, db_column="birthYear", max_length=255, null=True
                    ),
                ),
                (
                    "deathyear",
                    models.CharField(
                        blank=True, db_column="deathYear", max_length=255, null=True
                    ),
                ),
                (
                    "primaryprofession",
                    models.CharField(
                        blank=True,
                        db_column="primaryProfession",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "knownfortitles",
                    models.CharField(
                        blank=True,
                        db_column="knownForTitles",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "person-short",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RatingShort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "averagerating",
                    models.CharField(
                        blank=True, db_column="averageRating", max_length=255, null=True
                    ),
                ),
                (
                    "numvotes",
                    models.CharField(
                        blank=True, db_column="numVotes", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "rating-short",
                "managed": True,
            },
        ),
    ]
