# Generated by Django 5.0 on 2023-12-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                ("directors", models.CharField(blank=True, max_length=255, null=True)),
                ("writers", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "crew",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nconst", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "primaryname",
                    models.CharField(
                        blank=True, db_column="primaryName", max_length=255, null=True
                    ),
                ),
                (
                    "birthyear",
                    models.CharField(
                        blank=True, db_column="birthYear", max_length=255, null=True
                    ),
                ),
                (
                    "deathyear",
                    models.CharField(
                        blank=True, db_column="deathYear", max_length=255, null=True
                    ),
                ),
                (
                    "primaryprofession",
                    models.CharField(
                        blank=True,
                        db_column="primaryProfession",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "knownfortitles",
                    models.CharField(
                        blank=True,
                        db_column="knownForTitles",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "name",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Principals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                ("ordering", models.CharField(blank=True, max_length=255, null=True)),
                ("nconst", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("job", models.CharField(blank=True, max_length=255, null=True)),
                ("characters", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "principals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "averagerating",
                    models.CharField(
                        blank=True, db_column="averageRating", max_length=255, null=True
                    ),
                ),
                (
                    "numvotes",
                    models.CharField(
                        blank=True, db_column="numVotes", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "rating",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "titletype",
                    models.CharField(
                        blank=True, db_column="titleType", max_length=255, null=True
                    ),
                ),
                (
                    "primarytitle",
                    models.CharField(
                        blank=True, db_column="primaryTitle", max_length=255, null=True
                    ),
                ),
                (
                    "originaltitle",
                    models.CharField(
                        blank=True, db_column="originalTitle", max_length=255, null=True
                    ),
                ),
                (
                    "isadult",
                    models.CharField(
                        blank=True, db_column="isAdult", max_length=255, null=True
                    ),
                ),
                (
                    "startyear",
                    models.CharField(
                        blank=True, db_column="startYear", max_length=255, null=True
                    ),
                ),
                (
                    "endyear",
                    models.CharField(
                        blank=True, db_column="endYear", max_length=255, null=True
                    ),
                ),
                (
                    "runtimeminutes",
                    models.CharField(
                        blank=True,
                        db_column="runtimeMinutes",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("genres", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "title",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="CastShort",
        ),
        migrations.DeleteModel(
            name="FilmShort",
        ),
        migrations.DeleteModel(
            name="PersonFilmShort",
        ),
        migrations.DeleteModel(
            name="PersonShort",
        ),
        migrations.DeleteModel(
            name="RatingShort",
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.DeleteModel(
            name="Film",
        ),
    ]
