# Generated by Django 5.0 on 2023-12-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_crew_name_principals_rating_title_delete_castshort_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoubanTop250",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "primarytitle",
                    models.CharField(
                        blank=True, db_column="primaryTitle", max_length=255, null=True
                    ),
                ),
                (
                    "originaltitle",
                    models.CharField(
                        blank=True, db_column="originalTitle", max_length=255, null=True
                    ),
                ),
                ("urls", models.CharField(blank=True, max_length=255, null=True)),
                ("pictures", models.CharField(blank=True, max_length=255, null=True)),
                ("director", models.CharField(blank=True, max_length=255, null=True)),
                ("actor", models.CharField(blank=True, max_length=255, null=True)),
                ("startyear", models.CharField(blank=True, max_length=255, null=True)),
                ("nation", models.CharField(blank=True, max_length=255, null=True)),
                ("genres", models.CharField(blank=True, max_length=255, null=True)),
                ("score", models.CharField(blank=True, max_length=255, null=True)),
                ("scorenum", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "douban_top250",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "commentid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "primarytitle",
                    models.CharField(
                        blank=True, db_column="primaryTitle", max_length=255, null=True
                    ),
                ),
                ("tconst", models.CharField(blank=True, max_length=255, null=True)),
                ("userid", models.IntegerField(blank=True, null=True)),
                ("rating", models.CharField(blank=True, max_length=255, null=True)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "comment",
                "managed": True,
            },
        ),
    ]
