# Generated by Django 5.0 on 2023-12-16 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_doubantop250_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="primarytitle",
        ),
        migrations.AlterField(
            model_name="comment",
            name="commentid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="tconst",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="userid",
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
