# Generated by Django 5.0 on 2023-12-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("directors", models.CharField(blank=True, max_length=255, null=True)),
                ("writers", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "crew",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "nconst",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "primaryname",
                    models.CharField(
                        blank=True, db_column="primaryName", max_length=255, null=True
                    ),
                ),
                (
                    "birthyear",
                    models.CharField(
                        blank=True, db_column="birthYear", max_length=255, null=True
                    ),
                ),
                (
                    "deathyear",
                    models.CharField(
                        blank=True, db_column="deathYear", max_length=255, null=True
                    ),
                ),
                (
                    "primaryprofession",
                    models.CharField(
                        blank=True,
                        db_column="primaryProfession",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "knownfortitles",
                    models.CharField(
                        blank=True,
                        db_column="knownForTitles",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "name",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Principals",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("ordering", models.CharField(max_length=255)),
                ("nconst", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("job", models.CharField(blank=True, max_length=255, null=True)),
                ("characters", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "principals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "averagerating",
                    models.CharField(
                        blank=True, db_column="averageRating", max_length=255, null=True
                    ),
                ),
                (
                    "numvotes",
                    models.CharField(
                        blank=True, db_column="numVotes", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "rating",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "titletype",
                    models.CharField(
                        blank=True, db_column="titleType", max_length=255, null=True
                    ),
                ),
                (
                    "primarytitle",
                    models.CharField(
                        blank=True, db_column="primaryTitle", max_length=255, null=True
                    ),
                ),
                (
                    "originaltitle",
                    models.CharField(
                        blank=True, db_column="originalTitle", max_length=255, null=True
                    ),
                ),
                (
                    "isadult",
                    models.CharField(
                        blank=True, db_column="isAdult", max_length=255, null=True
                    ),
                ),
                (
                    "startyear",
                    models.CharField(
                        blank=True, db_column="startYear", max_length=255, null=True
                    ),
                ),
                (
                    "endyear",
                    models.CharField(
                        blank=True, db_column="endYear", max_length=255, null=True
                    ),
                ),
                (
                    "runtimeminutes",
                    models.CharField(
                        blank=True,
                        db_column="runtimeMinutes",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("genres", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "title",
                "managed": False,
            },
        ),
    ]
